FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt \
 && python -m nltk.downloader stopwords

COPY preprocessing.py ./preprocessing.py
COPY api/app.py ./api/app.py

EXPOSE 5000

CMD ["python", "api/app.py"]
