FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt \
 && python -m nltk.downloader stopwords

COPY preprocessing.py ./preprocessing.py
COPY dask/predict.py ./dask/predict.py

CMD ["python", "dask/predict.py"]
