FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY data/ ./data/
COPY dask/ingest.py ./dask/ingest.py

CMD ["python", "dask/ingest.py"]
